# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richwoods Worship Tech/Arts
email: jason@jterhorst.com
description: > # this means to ignore newlines until "baseurl:"
  Tutorials and teaching info for using video software and equipment at Richwoods Christian Church.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://richwoods.github.com/tutorials" # the base hostname & protocol for your site
twitter_username: jterhorst
github_username:  jterhorst

# Build settings
markdown: kramdown
gems: ['jekyll_video_tag']